### ISSUE TITLE
main 페이지 수정사항

### ISSUE THREAD

**Issue by syg4806** [ThinLineIT/CtrlF_Frontend#1]
<img width="1505" alt="스크린샷 2021-05-19 오후 5 13 42" src="https://user-images.githubusercontent.com/56154295/118779494-0f05b600-b8c6-11eb-8719-25421ff91088.png">

1. 커넵로고가 잘 안보이는 것 같아요.

2. 포커스 생기면(검색하려고 클릭했을때) 원래 써져있던 내용이 지워지고 힌트로 보이면 좋을 것 같아요.

3. 이슈 좌우 간격 조절해주세요!

**Comment by JSH-data** [comment]
2. 힌트 작업
