### ISSUE TITLE
Page Detail 페이지 

### ISSUE THREAD

**Issue by syg4806** [ThinLineIT/CtrlF_Frontend#2]
<img width="1043" alt="스크린샷 2021-05-19 오후 5 22 54" src="https://user-images.githubusercontent.com/56154295/118780569-285b3200-b8c7-11eb-9c10-5d9e2d8cedfa.png">

1. 처음 페이지 켜지면, 첫 토픽의 첫 주제가 선택되어서 보여지게 해주세요

2. 검색 부분 글씨체 맞춰주세요

3. 아이콘 디자인과 동일한 것으로 변경 및 추가해주세요

**Comment by JSH-data** [comment]
1. 미작업
+ 힌트 작업
