### ISSUE TITLE
Issue list 페이지

### ISSUE THREAD

**Issue by syg4806** [ThinLineIT/CtrlF_Frontend#4]
<img width="947" alt="스크린샷 2021-05-19 오후 5 29 26" src="https://user-images.githubusercontent.com/56154295/118781219-c51dcf80-b8c7-11eb-8ec4-29e3ea92cce0.png">

1. 필터 부분 기능 추가

**Comment by JSH-data** [comment]
핕터는 드롭박스로 바꿔달라는 말씀이신가요?

**Comment by syg4806** [comment]
> 핕터는 드롭박스로 바꿔달라는 말씀이신가요?

맞습니당
