### ISSUE TITLE
탭 이름 final 표기되는 현상

### ISSUE THREAD

**Issue by syg4806** [ThinLineIT/CtrlF_Frontend#7]
<img width="249" alt="스크린샷 2021-05-22 오후 3 25 20" src="https://user-images.githubusercontent.com/56154295/119216974-f984cc00-bb11-11eb-8ec1-134f4a384fff.png">

크롭 상단 탭 이름에 final 표시되고 있음
각 화면 컨택스트 맞게 표현되게 변경

**Comment by JSH-data** [comment]
아이콘, 페이지 타이틀 추가
