### ISSUE TITLE
Issue 페이지 버그

### ISSUE THREAD

**Issue by syg4806** [ThinLineIT/CtrlF_Frontend#9]
1. Issue Request 해도 Issue가 추가 안되는 것 같습니다.
2. Issue 페이지에서 새로고침하면 404에러가 발생합니다.

**Comment by JSH-data** [comment]
1. 이번 0.1.0 버전에서는 추가기능이 들어가지 않는다고 하셔서 따로 구현하지 않았었습니다. 가능한 오늘 안으로 구현해보겠습니다.

2. github페이지가 SPA를 지원하지 않는다고 합니다. 때문에 모든 페이지에서 동일한 현상이 나타나는 것을 확인했습니다. 이 문제를 해결하기 위해 임시 방편으로  404.html을 조작하여 우회하는 방식을 사용했습니다.
